### PR TITLE
Fix script setup

### PR DESCRIPTION
**Pull request by patrickmelix**
This is what I found. Not sure on how to include the bash scripts yet. Also this is not automatic, every new item therefore needs a line in pyproject.toml... Not ideal.

### CODE REVIEW

**Comment by hweiske** [comment]
If you want to incorporate bash scripts, the only thing i can find is to create simple python wrapper using `subprocess`.

**Comment by hweiske** [comment]
Also couldn't find a wildcard way without using `setup.py`.

**Comment by patrickmelix** [comment]
Mmmh, the bash scripts don't have any way of printing nice help messages now... But I guess we can fix this later.

**Review by hweiske — APPROVED** [review]
Alrighty

**Comment by patrickmelix** [comment]
Well, you were fast :-D

**Pull request merged**
